name: forms_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  formz: ^0.8.0
  go_router: ^14.3.0
  bloc_test: ^9.1.7

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.25.7

flutter:
  uses-material-design: true
